# Github Actions
# Copyright (c) JP Record

name: Github Actions Basics
env:
  APPLICATION_NAME    : "MyFlask" 
  DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"
on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest 

    steps:
      - name: Print Barior in Testing
        run: echo "Hello from Testing job"

      - name: Execute few commands
        run: |
          echo "Hello 1"
          echo "Hello 2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
          
      - name: List current folder
        run: ls -la

      - name: Git clone my repo
        uses: actions/checkout@v1

      - name: List current folder
        run: ls -la 
  
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1 : "Job level Variable1"
      VAR2 : "Job level Variable2"
      
    steps:
      - name: Print Barior in Deploy
        run: echo "Hello from Deploy job"

      - name: Print env vars
        run: |
          echo "Var1 = ${{ env.VAR1 }}"
          echo "Var2 = ${{ env.VAR2 }}"
          echo "Var3 = $LOCAL_VAR"
        env:
          LOCAL_VAR: "This is Super local ENV. variable"
          
        
      - name: Printing Deployment package
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"

      - name: Test some packages there 1
        run: aws --version
        
      - name: Test some packages there 2
        run: zip --version
